$lgAvailable = "Beschikbaar"
$lgBusy = "Bezet"
$lgOnThePhone = "Aan de telefoon"
$lgAway = "Afwezig"
$lgBeRightBack = "Zo terug"
$lgDoNotDisturb = "Niet storen"
$lgPresenting = "Presenteren"
$lgFocusing = "Focussen"
$lgInAMeeting = "In een vergadering"
$lgOffline = "Offline"
$lgNotInACall = "Niet in gesprek"
$lgInACall = "In gesprek"
# sensor.teams_cam_status
$lgCameraOn = "Aan"
$lgCameraOff = "Uit"
